Repository Tinkoff/neptune, pull requests merged in 2021-09, with the labels that each got.

#270 0.19.5-ALPHA
  .github/workflows/gradle.yml
  allure.integration/README.md
  allure.integration/build.gradle
  allure.testng.bridge/README.md
  allure.testng.bridge/build.gradle
  build.gradle
  check/README.md
  check/build.gradle
  core.api/README.md
  core.api/build.gradle
  data.base.api/build.gradle
  http.api/README.md
  http.api/build.gradle
  kafka/README.md
  kafka/build.gradle
  neptune.swagger.codegen/build.gradle
  neptune.swagger.codegen/doc/rus/README.MD
  rabbit.mq/README.MD
  rabbit.mq/build.gradle
  retrofit2/README.md
  retrofit2/build.gradle
  selenium/README.md
  selenium/build.gradle
  testng.integration/README.md
  testng.integration/build.gradle
Labels: DevOps, dependencies

#272 0.19.6-ALPHA
  allure.integration/build.gradle
  allure.testng.bridge/build.gradle
  build.gradle
  check/build.gradle
  core.api/build.gradle
  data.base.api/build.gradle
  http.api/build.gradle
  kafka/build.gradle
  rabbit.mq/build.gradle
  retrofit2/build.gradle
  selenium/build.gradle
  testng.integration/build.gradle
Labels: bug, dependencies

#275 Database abstractions
  README.md
  database.abstractions/README.md
  database.abstractions/build.gradle
  database.abstractions/doc/eng/README.md
  database.abstractions/doc/rus/CONTEXT.md
  database.abstractions/doc/rus/README.md
  database.abstractions/src/main/java/ru/tinkoff/qa/neptune/database/abstractions/AbstractDatabaseStepContext.java
  database.abstractions/src/main/java/ru/tinkoff/qa/neptune/database/abstractions/InsertQuery.java
  database.abstractions/src/main/java/ru/tinkoff/qa/neptune/database/abstractions/OrmCompatible.java
  database.abstractions/src/main/java/ru/tinkoff/qa/neptune/database/abstractions/SelectQuery.java
  database.abstractions/src/main/java/ru/tinkoff/qa/neptune/database/abstractions/UpdateAction.java
  settings.gradle
Labels: enhancement, data base
